### ISSUE TITLE
api key 的隐私问题

### ISSUE THREAD

**Issue by ckhis-droid** [Dimitri2020007/heroku-vless#3]
为什么搭建的时候都需要填写cloudflare的api key和cloudflare的地址呢？可以不需要填写就搭建呢？这是什么原因？？请作者回复一下...

**Comment by Dimitri2020007** [comment]
使用api key和email是为了注册acme tls的.

**Comment by ckhis-droid** [comment]
> 使用api key和email是为了注册acme tls的.
> 
> 不填写请将caddyfile中的tls改成internal并去掉app.json的api_key和email变量
> 
> 重新部署即可

那帐号那里还需要改成tls吗？帐号填写还需要修改哪些呢？小白请见谅...

**Comment by Dimitri2020007** [comment]
caddyfile

```
tls $EMAIL {
    dns cloudflare $API_KEY
    resolvers 8.8.4.4
}
```
改成
```
tls internal
```

app.json去掉api_key和email变量重新部署就行

**Comment by ckhis-droid** [comment]
> caddyfile
> 
> ```
> tls $EMAIL {
>     dns cloudflare $API_KEY
>     resolvers 8.8.4.4
> }
> ```
> 
> 改成
> 
> ```
> tls internal
> ```
> 
> app.json去掉api_key和email变量重新部署就行
那是不是TLS
